services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: maze-of-me-api
    container_name: maze-of-me-api
    volumes:
      - ./:/var/www/html
    ports:
      - "3000:8000"
    environment:
      - DB_HOST=db
      - DB_DATABASE=maze_of_me
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: maze-of-me-api-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=maze_of_me
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
